export const config = {
  MAX_MESSAGES_PER_SESSION: 8,
  SESSION_DURATION_MS: 15 * 60 * 1000,
  SESSION_COOLDOWN_MS: 30 * 60 * 1000,
  AI_TIMEOUT_MS: 8000,
  CONTENT_CACHE_TTL_MS: 60 * 60 * 1000,
  REENGAGEMENT_SILENCE_DAYS: 3,
  REENGAGEMENT_COOLDOWN_DAYS: 7,
  ENTITLEMENT_ID: 'harlo_access',
  CONTENT_VERSION: 'v1',
} as const;
